apiVersion: v1
kind: Service
metadata:
  name: aws-integration-demo-service
spec:
  selector:
    app: aws-integration-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer