version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - connect-net

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - connect-net

networks:
  connect-net:
    driver: bridge