version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - app-data:/app/data
    networks:
      - demo-network
    environment:
      - NODE_ENV=production

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - demo-network

volumes:
  app-data:
  redis-data:

networks:
  demo-network:
    driver: bridge