version: '3.8'

services:
  app:
    image: docker-swarm-demo:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    environment:
      - NODE_ENV=production

  redis:
    image: redis:6.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure