apiVersion: v1
kind: Service
metadata:
  name: k8s-integration-demo-service
spec:
  selector:
    app: k8s-integration-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer