# Main Learning Points: Pushing to Multiple Registries
# Build and push a Docker image to Docker Hub, AWS ECR, and Google Artifact Registry.

name: Push to Registries

on:
  push:
    branches: [ main ]

jobs:
  push-to-registries:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image
      - name: Build Docker image
        run: docker build -t docker-registries-demo:latest .

      # Push to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker tag docker-registries-demo:latest ${{ secrets.DOCKERHUB_USERNAME }}/docker-registries-demo:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/docker-registries-demo:latest

      # Push to AWS ECR
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Push to AWS ECR
        run: |
          docker tag docker-registries-demo:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/docker-registries-demo:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/docker-registries-demo:latest

      # Push to Google Artifact Registry
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Push to Google Artifact Registry
        run: |
          docker tag docker-registries-demo:latest us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-registries-demo/docker-registries-demo:latest
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/docker-registries-demo/docker-registries-demo:latest